version: '3'
services:
  web:
    container_name: ${WEB_HOST}
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - WEB_IMAGE_TAG=${WEB_IMAGE_TAG}
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    restart: always
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    command:
            - /usr/bin/odoo
            - --dev=reload,qweb,werzeug,xml
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-db-data:
  odoo-web-data: